package com.cyagent.supportcopilot.audit;

public enum AuditAction {
	TICKET_CREATED,
	TICKET_UPDATED,
	TICKET_UNASSIGNED,
	TICKET_NOTE_ADDED,
	ANALYSIS_PERSISTED,
	ANALYSIS_REVIEW_APPROVED,
	ANALYSIS_REVIEW_EDITED,
	ANALYSIS_REVIEW_REJECTED,
	KNOWLEDGE_RELEASE_DRAFT_CREATED,
	KNOWLEDGE_RELEASE_APPROVED,
	KNOWLEDGE_RELEASE_PUBLISHED,
	KNOWLEDGE_RELEASE_ROLLED_BACK
}
