package com.cyagent.supportcopilot.audit;

public enum AuditAction {
	TICKET_CREATED,
	TICKET_UPDATED,
	TICKET_UNASSIGNED,
	ANALYSIS_PERSISTED,
	ANALYSIS_REVIEW_APPROVED,
	ANALYSIS_REVIEW_EDITED,
	ANALYSIS_REVIEW_REJECTED
}
